name: Cross-Compile for Multiple Architectures

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
    - name: Set up dependencies
      run: sudo apt-get update

    - name: Install cross-compilers and dependencies
      run: |
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          gcc-x86-64-linux-gnu \
          gcc-mingw-w64-x86-64 \
          cmake \
          zip \
          tree

    - name: Checkout nunicode repository from Bitbucket (specific tag)
      run: |
        git clone https://bitbucket.org/alekseyt/nunicode.git
        cd nunicode
        git checkout 1.11


    - name: Build for linux-x86_64
      run: |
        cd nunicode/staging
        mkdir -p build_amd64
        (cd build_amd64 && cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../cmake/Toolchain-Amd64.cmake)
        (cd build_amd64 && tree)
        (cd build_amd64 && make nusqlite3)