name: Cross-Compile for Multiple Architectures

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository (nunicode-binaries)
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: sudo apt-get update

    - name: Install cross-compilers and dependencies
      run: |
        sudo apt-get install -y \
          gcc-x86-64-linux-gnu \
          gcc-mingw-w64-x86-64 \
          cmake \
          zip \
          tree

    - name: Checkout nunicode repository from Bitbucket (specific tag)
      run: |
        git clone https://bitbucket.org/alekseyt/nunicode.git
        cd nunicode
        git checkout 1.11

    - name: Copy toolchain files from this repository
      run: |
        cp cmake/Toolchain-Mingw64.cmake nunicode/cmake/


    - name: Build for linux-x86_64
      run: |
        cd nunicode/staging
        mkdir -p build_amd64
        (cd build_amd64 && cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../cmake/Toolchain-Amd64.cmake)
        (cd build_amd64 && tree)
        (cd build_amd64 && make nusqlite3)

    - name: Build for win64
      run: |
        cd nunicode/staging
        mkdir -p build_mingw64
        (cd build_mingw64 && cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../../cmake/Toolchain-Mingw64.cmake)
        (cd build_mingw64 && cmake ../../sqlite3 -DSQLITE3_INCLUDE_DIR=/usr/include -DCMAKE_BUILD_TYPE=Release -D-DCMAKE_TOOLCHAIN_FILE=../../cmmake/Toolchain-Mingw64.cmake)
        (cd build_mingw64 && make nusqlite3)