name: Create a nunicode-binaries release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-binaries.yaml

  create-release:
    needs: trigger-build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        
      - name: Create a release
        id: create-release
        uses: actions/create-release@v1        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Zip Subdirectories to Root
        run: |
          for dir in libnusqlite3-*/; do
            if [ -d "$dir" ]; then
              cd "$dir"
              zip -r "../${dir%/}.zip" *  # Zip the contents, not the directory itself
              cd ..
            fi
          done      

      - name: Upload ZIP Files as Release Assets
        run: |
          for file in *.zip; do
            echo "Uploading $file..."
            gh release upload ${{ github.ref }} "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
