name: Create a nunicode-binaries release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-binaries.yaml

  create-release:
    needs: trigger-build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        
      - name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      
