name: Create a nunicode-binaries release

on:
  push:
    tags:
      - '*'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-binaries.yaml

  create-release:
    needs: trigger-build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        
      - name: Zip Subdirectories to Root
        run: |
          for dir in libnusqlite3-*/; do
            if [ -d "$dir" ]; then
              cd "$dir"
              zip -r "../${dir%/}.zip" *  # Zip the contents, not the directory itself
              cd ..
            fi
          done      

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: '*.zip'
      
